language: java
jdk: oraclejdk7

install: mvn package -Pmcp-final-unix -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/515/XKi-6poJeJINy51JH0bWKXZh

env:
  global:
    - secure: "YWDQXr6orafZjQ179p0RYVngDXUVFFXOOunkZUIgzZ3QkIRuyjQTjX1gbNOy7/nFfwR5jcMYtOg0R2H1zqrjdrRTBn9kjU9FddgsDTKuQetrsC2zsQON5KS0zE/JyMUKfenXuqw8SxsSEGhK8Ik0EIMCjjjmDoxxXGM1IXUdCkQ="
    - secure: "ewDlug3sHoIrUYs68H9fy2zKni9RCIMfkZnYfMTbHwh+fM4ISFO4asNrKOufGdvfMo4jQLfuRsUtlvaHqvx2OwHuB3ymjS1pOKkj1RLee/dFFd1KAnbH8Mb2ANOKMRv3y6YO+c9R1w5Fqm9woz4ONmO0ukrSNR2qMjOntbuQRHM="
